name: Telegram Bot Cron Job

on:
  schedule:
    - cron: '0 */6 * * *'  # This cron expression runs every 6 hours (360 minutes)
  workflow_dispatch:   # Allows manual trigger of the action if needed

jobs:
  run-bot:
    runs-on: lodu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telebot && chmod +x * # Make sure you have a requirements.txt for your dependencies

      - name: Run the Telegram Bot
        run: |
          python IPxVIP.py.py  # Replace with your script file name
        
